locallibrary/catalog/urls.py
from . import views
from django.conf.urls import url

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^books/$', views.BookListView.as_view(), name='books'),
    url(r'^book/(?P<pk>\d+)$', views.BookDetailView.as_view(), name='book-detail'),
    url(r'^authors/$', views.AuthorListView.as_view(), name='authors'),
    url(r'^author/(?P<pk>\d+)$', views.AuthorDetailView.as_view(), name='author-detail'),
    url(r'^mybooks/$', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    url(r'^borrowed/$', views.AllLoanedBooksListView.as_view(), name='all-borrowed'),
    url(r'^book/(?P<pk>[-\w]+)/renew/$', views.renew_book_librarian, name='renew-book-librarian'),
    url(r'^author/create/$', views.AuthorCreate.as_view(), name='author_create'),
    url(r'^author/(?P<pk>\d+)/update/$', views.AuthorUpdate.as_view(), name='author_update'),
    url(r'^author/(?P<pk>\d+)/delete/$', views.AuthorDelete.as_view(), name='author_delete'),
    url(r'^book/create/$', views.BookCreate.as_view(), name='book_create'),
    url(r'^book/(?P<pk>\d+)/update/$', views.BookUpdate.as_view(), name='book_update'),
    url(r'^book/(?P<pk>\d+)/delete/$', views.BookDelete.as_view(), name='book_delete'),
]

locallibrary/locallibrary/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='/catalog/', permanent=True)),
    path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

locallibrary/catalog/models.py
from django.db import models
from django.urls import reverse
import uuid
from django.contrib.auth.models import User
from datetime import date

class Genre(models.Model):
    """
    Model representing a book genre (e.g. Science Fiction, Non Fiction).
    """
    name = models.CharField(max_length=200, help_text="Enter a book genre (e.g. Science Fiction, French Poetry etc.)")

    def __str__(self):
        """
        String for representing the Model object (in Admin site etc.)
        """
        return self.name


class Book(models.Model):
    """
    Model representing a book (but not a specific copy of a book).
    """
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    # Foreign Key used because book can only have one author, but authors can have multiple books
    # Author as a string rather than object because it hasn't been declared yet in the file.
    summary = models.TextField(max_length=1000, help_text="Enter a brief description of the book")
    isbn = models.CharField('ISBN',max_length=13, help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    genre = models.ManyToManyField(Genre, help_text="Select a genre for this book")
    # ManyToManyField used because genre can contain many books. Books can cover many genres.
    # Genre class has already been defined so we can specify the object above.

    def __str__(self):
        """
        String for representing the Model object.
        """
        return self.title


    def get_absolute_url(self):
        """
        Returns the url to access a particular book instance.
        """
        return reverse('book-detail', args=[str(self.id)])

    def display_genre(self):
        """
        Creates a string for the Genre. This is required to display genre in Admin.
        """
        return ', '.join([genre.name for genre in self.genre.all()[:3]])

    display_genre.short_description = 'Genre'


class BookInstance(models.Model):
    """
    Model representing a specific copy of a book (i.e. that can be borrowed from the library).
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text="Unique ID for this particular book across whole library")
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Обслуживание'),
        ('o', 'Арендован'),
        ('a', 'Доступен'),
        ('r', 'Забронирован'),
    )

    status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True, default='m', help_text='Book availability')

    class Meta:
        ordering = ["due_back"]
        permissions = (("can_mark_returned", "Set book as returned"),)


    def __str__(self):
        """
        String for representing the Model object
        """
        return f'{self.id} ({self.book.title})'

    def book_title(self):
        return str(self.book.title)

    def due_back_format(self):
        return '.'.join((str(self.due_back)).split('-'))

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False


class Author(models.Model):
    """
    Model representing an author.
    """
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    def get_absolute_url(self):
        """
        Returns the url to access a particular author instance.
        """
        return reverse('author-detail', args=[str(self.id)])


    def __str__(self):
        """
        String for representing the Model object.
        """
        return f'{self.first_name} {self.last_name}'

    def life_period(self):
        return '.'.join((str(self.date_of_birth)).split('-')) + (' - ' + '.'.join((str(self.date_of_death)).split('-')) if self.date_of_death else '')

locallibrary/catalog/forms.py
from django import forms

from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
import datetime #for checking renewal date range.

from catalog.models import Author, Book


class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(help_text="Введите дату между текущим моментом и через 8 недель (по умолчанию 3).", label="Обновлённая дата:")

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        #Проверка того, что дата не выходит за "нижнюю" границу (не в прошлом).
        if data < datetime.date.today():
            raise ValidationError(_('Неверная дата - значение в прошлом'))

        #Проверка того, то дата не выходит за "верхнюю" границу (+8 недель).
        if data > datetime.date.today() + datetime.timedelta(weeks=8):
            raise ValidationError(_('Неверная дата - значение более чем через 8 недель.'))

        # Помните, что всегда надо возвращать "очищенные" данные.
        return data

class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ('first_name', 'last_name', 'date_of_birth', 'date_of_death')
        labels = {
            'first_name': _('Имя'),
            'last_name': _('Фамилия'),
            'date_of_birth': _('Дата рождения'),
            'date_of_death': _('Дата смерти'),
        }

class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ('title', 'author', 'summary', 'isbn', 'genre')
        labels = {
            'title': _('Название'),
            'author': _('Автор'),
            'summary': _('Краткое описание'),
            'isbn': _('ISBN'),
            'genre': _('Жанр'),
        }
        help_texts = {
            'summary': _('Введите краткое описание книги'),
            'isbn': _('<a href="https://www.isbn-international.org/content/what-isbn">Номер ISBN</a> из 13 символов'),
            'genre': _('Выберите жанр для книги'),
        }

locallibrary/catalog/views.py
from django.shortcuts import render
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.decorators import permission_required
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
import datetime
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from .forms import RenewBookForm, AuthorForm, BookForm

from .models import Book, Author, BookInstance, Genre

def index(request):
    """
    Функция отображения для домашней страницы сайта.
    """
    # Генерация "количеств" некоторых главных объектов
    num_books=Book.objects.all().count()
    num_instances=BookInstance.objects.all().count()
    # Доступные книги (статус = 'a')
    num_instances_available=BookInstance.objects.filter(status__exact='a').count()
    num_authors=Author.objects.count()  # Метод 'all()' применён по умолчанию.

    # Number of visits to this view, as counted in the session variable.
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    # Render the HTML template index.html with the data in the context variable.
    return render(
        request,
        'index.html',
        context={'num_books': num_books, 'num_instances': num_instances,
                 'num_instances_available': num_instances_available, 'num_authors': num_authors,
                 'num_visits': num_visits},  # num_visits appended
    )

class BookListView(generic.ListView):
    model = Book
    paginate_by = 10

    def get_queryset(self):
        return Book.objects.order_by('author')

class BookDetailView(generic.DetailView):
    model = Book

class AuthorListView(generic.ListView):
    model = Author
    paginate_by = 10

class AuthorDetailView(generic.DetailView):
    model = Author

class LoanedBooksByUserListView(LoginRequiredMixin,generic.ListView):
    model = BookInstance
    template_name ='catalog/bookinstance_list_borrowed_user.html'
    paginate_by = 10

    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')

class AllLoanedBooksListView(PermissionRequiredMixin, generic.ListView):
    permission_required = 'catalog.can_mark_returned'
    model = BookInstance
    template_name = 'catalog/all_borrowed.html'
    paginate_by = 10

    def get_queryset(self):
        return BookInstance.objects.filter(status__exact='o').order_by('due_back')

@permission_required('catalog.can_mark_returned')
def renew_book_librarian(request, pk):
    """
    View function for renewing a specific BookInstance by librarian
    """
    book_inst = get_object_or_404(BookInstance, pk=pk)

    # If this is a POST request then process the Form data
    if request.method == 'POST':

        # Create a form instance and populate it with data from the request (binding):
        form = RenewBookForm(request.POST)

        # Check if the form is valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required (here we just write it to the model due_back field)
            book_inst.due_back = form.cleaned_data['renewal_date']
            book_inst.save()

            # redirect to a new URL:
            return HttpResponseRedirect(reverse('all-borrowed') )

    # If this is a GET (or any other method) create the default form.
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewBookForm(initial={'renewal_date': proposed_renewal_date,})

    return render(request, 'catalog/book_renew_librarian.html', {'form': form, 'bookinst':book_inst})

class AuthorCreate(PermissionRequiredMixin, CreateView):
    permission_required = 'catalog.can_mark_returned'
    model = Author
    form_class = AuthorForm

class AuthorUpdate(PermissionRequiredMixin, UpdateView):
    permission_required = 'catalog.can_mark_returned'
    model = Author
    form_class = AuthorForm

class AuthorDelete(PermissionRequiredMixin, DeleteView):
    permission_required = 'catalog.can_mark_returned'
    model = Author
    success_url = reverse_lazy('authors')

class BookCreate(PermissionRequiredMixin, CreateView):
    permission_required = 'catalog.can_mark_returned'
    model = Book
    form_class = BookForm

class BookUpdate(PermissionRequiredMixin, UpdateView):
    permission_required = 'catalog.can_mark_returned'
    model = Book
    form_class = BookForm

class BookDelete(PermissionRequiredMixin, DeleteView):
    permission_required = 'catalog.can_mark_returned'
    model = Book
    success_url = reverse_lazy('books')

locallibrary/catalog/templates/catalog/all_borrowed.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Арендованные книги</h1>

    {% if bookinstance_list %}
    <table class="mt-4 h5 display-table">
        <tr class="text-secondary">
            <td>Название</td>
            <td>Дата возврата</td>
            <td>Заёмщик</td>
        </tr>
      {% for bookinst in bookinstance_list %}
        <tr>
            <td><a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a></td>
            <td><span class="{% if bookinst.is_overdue %}text-danger{% endif %}"> {{ bookinst.due_back_format }}</span></td>
            <td>{{bookinst.borrower}}</td>
            {% if perms.catalog.can_mark_returned %}
                <td><a href="{% url 'renew-book-librarian' bookinst.id %}">Редактировать</a></td>
            {% endif %}
        </tr>
      {% endfor %}
    </table>

    {% else %}
      <p class="h5">Нет арендованных книг.</p>
    {% endif %}
{% endblock %}

locallibrary/catalog/templates/catalog/author_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Удалить автора</h1>

  <p class="h5 text-danger">Вы уверены, что хотите удалить автора:</p>
    <p class="mt-2 mb-2 h3 text-danger">{{ author }}?</p>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Да, удалить." />
  </form>
{% endblock %}

locallibrary/catalog/templates/catalog/author_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>{{ author }}</h1>
  <h2>({{ author.life_period }})</h2>

  <span class="h5"><a href="{% url 'author_update' author.pk %}">Редактировать</a> <a class="text-danger" href="{% url 'author_delete' author.pk %}">Удалить</a></span>

  <div style="margin-left:20px;margin-top:20px">
    <h3>Книги</h3>

    {% if author.book_set.all %}
        {% for book in author.book_set.all %}
        <hr>
        <a href="{{ book.get_absolute_url }}">{{ book.title }} ({{book.display_genre}})</a>
        <p class="mt-2 text-secondary ml-3">{{ book.summary }}</p>
        {% endfor %}
    {% else %}
        <p class="h5 text-secondary mt-3">У этого автора нет книг.</p>
    {% endif %}
  </div>
{% endblock %}

locallibrary/catalog/templates/catalog/author_form.html
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post">
      {% csrf_token %}
      <table>
      {{ form.as_table }}
      </table>
      <input type="submit" value="Сохранить" />
  </form>
{% endblock %}

locallibrary/catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Список авторов</h1>

    {% if author_list %}
    <table class="mt-4 h5 display-table">
        <tr class="text-secondary">
            <td>Имя</td>
            <td>Дата рождения</td>
            <td>Дата смерти <span class="h4">☠</span></td>
        </tr>
      {% for author in author_list %}
      <tr>
          <td><a href="{{ author.get_absolute_url }}">{{ author }}</a></td>
          <td>{{ author.date_of_birth }}</td>
          <td>{% if author.date_of_death %} {{ author.date_of_death }} {% else %} --- {% endif %}</td>
      </tr>
      {% endfor %}

    </table>
    {% else %}
      <p>В библиотеке нет записей об авторах.</p>
    {% endif %}
{% endblock %}

locallibrary/catalog/templates/catalog/book_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Удалить книгу</h1>

    <p class="h5 text-danger">Вы уверены, что хотите удалить книгу:</p>
    <p class="mt-2 mb-2 h3 text-danger">"{{ book }}"?</p>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Да, удалить." />
  </form>
{% endblock %}

locallibrary/catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Название: {{ book.title }}</h1>
    <span class="h5"><a href="{% url 'book_update' book.pk %}">Редактировать</a> <a class="text-danger" href="{% url 'book_delete' book.pk %}">Удалить</a></span>

  <p class="mt-4"><strong>Автор:</strong> <a href="{% url 'author-detail' book.author.pk %}">{{ book.author }}</a>
  <p><strong>Описание:</strong> {{ book.summary }}</p>
  <p><strong>Жанр:</strong> {% for genre in book.genre.all %} {{ genre }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Экземпляры</h4>
    
    {% if book.bookinstance_set.all %}
        {% for copy in book.bookinstance_set.all %}
        <hr>
        <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
        {% if copy.status != 'a' and copy.status != 'm' %}<p><strong>Дата возврата:</strong> {{copy.due_back_format}}</p>{% endif %}
        <p><strong>Подпись:</strong> {{copy.imprint}}</p>
        <p class="text-muted"><strong>ID:</strong> {{copy.id}}</p>
        {% endfor %}
    {% else %}
        <p class="h5 mt-3 text-secondary">У этой книги нет экземпляров.</p>
    {% endif %}
  </div>
{% endblock %}

locallibrary/catalog/templates/catalog/book_form.html
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post">
      {% csrf_token %}
      <table>
      {{ form.as_table }}
      </table>
      <input type="submit" value="Сохранить" />
  </form>
{% endblock %}

locallibrary/catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Список книг</h1>

    {% if book_list %}
    <table class="mt-4 h5 display-table">
        <tr class="text-secondary">
            <td>Название</td>
            <td>Автор</td>
        </tr>
      {% for book in book_list %}
      <tr>
        <td><a href="{{ book.get_absolute_url }}">{{ book.title }}</a></td>
        <td>{{book.author}}</td>
      </tr>
      {% endfor %}

    </table>
    {% else %}
      <p class="h5">В библиотеке нет книг.</p>
    {% endif %}
{% endblock %}

locallibrary/catalog/templates/catalog/book_renew_librarian.html
{% extends "base_generic.html" %}
{% block content %}

    <h1>Редактировать: {{bookinst.book.title}}</h1>
    <p class="mt-4 h5">Заёмщик: {{bookinst.borrower}}</p>
    <p class="h5 {% if bookinst.is_overdue %} text-danger{% endif %}">Дата возврата: {{bookinst.due_back_format}}</p>

    <form action="" method="post">
        {% csrf_token %}
        <table>
        {{ form }}
        </table>
        <input type="submit" value="Сохранить" />
    </form>

{% endblock %}

locallibrary/catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Мои книги</h1>

    {% if bookinstance_list %}
    <table class="mt-4 h5 display-table">
        <tr class="text-secondary">
            <td>Название</td>
            <td>Дата возврата</td>
        </tr>
      {% for bookinst in bookinstance_list %}
      <tr>
        <td><a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a></td>
        <td><span class="{% if bookinst.is_overdue %}text-danger{% endif %}"> {{ bookinst.due_back_format }} </span></td>
      </tr>
      {% endfor %}
    </table>

    {% else %}
      <p class="h5">У вас нет арендованных книг.</p>
    {% endif %}
{% endblock %}